### ISSUE TITLE
exportar a html5

### ISSUE THREAD

**Issue by jordibc** [appsforscience/ScienceQuiz#1]
Probar si podemos crear una app en html5 funcional con godot.

- [x] clonar y compilar el repositorio de godot
- [x] crear un proyecto y exportarlo a html5

**Comment by jordibc** [comment]
[] clonar y compilar el repositorio de godot
[] crear un proyecto y exportarlo a html5

**Comment by sagilca** [comment]
Cómo va?

**Comment by jordibc** [comment]
Tras mucho darle, funciona. Pero justo ha salido la release candidate 1 (https://godotengine.org/article/dev-snapshot-godot-3-0-rc-1) y debería ser más fácil.
