### ISSUE TITLE
hacer tutorial

### ISSUE THREAD

**Issue by jordibc** [appsforscience/ScienceQuiz#11]
- [x] pensar en cómo va a ser
- [x] implementarlo

**Comment by sagilca** [comment]
Posibilidad: el dino va hablando, pinchas en los bocadillos para que avance el texto, si pinchas en el dino te vuelve a salir el tutorial....

**Comment by sagilca** [comment]
Doc subido a https://docs.google.com/document/d/1DqgRE14tnL-apPpuyy7NSjcIjDNTcT7E9vK_2GmeWt8/edit
