### ISSUE TITLE
añadir estados de ánimo para dino

### ISSUE THREAD

**Issue by jordibc** [appsforscience/ScienceQuiz#14]
Que el monigote haga distintas cosas en distintos momentos (yes, no, happy).

**Comment by jordibc** [comment]
Hay que ver qué hace cuándo, y tener los sprites listos como pngs...

**Comment by sagilca** [comment]
Normal
Acierto: acertar pregunta
----------
Fallo: fallar pregunta
Sudado: cuando queden menos de 10 segundos
Hablando: al inicio de un bocadillo
Aburrido: menú principal sin hacer nada 
Superemocionado: al conseguir medalla

**Comment by FerFLB** [comment]
Animaciones hechas: 
Tiempo
No
Hablar
Dormido
Muy contento
Bostezo
Contento
Sí
Triste
Respirando
