### ISSUE TITLE
Pensar nombre para la app!

### ISSUE THREAD

**Issue by sagilca** [appsforscience/ScienceQuiz#30]

**Comment by jordibc** [comment]
Algunas propuestas tipo brainstorming:
* ¿Sabes de ciencia? (SDC)
* Las preguntas de ciencia
* 11F-quiz
* Ciencia a concurso
* A ciencia cierta

**Comment by jordibc** [comment]
Parece que gana "¿Sabes de ciencia?" (SdC).
