### ISSUE TITLE
añadirle algo de humor :)

### ISSUE THREAD

**Issue by jordibc** [appsforscience/ScienceQuiz#4]
que no se diga que somos unos estirados :P

**Comment by jordibc** [comment]
Nuestro amigo Dino acaba de aparecer. Es un avance! Creo que lo que más cambiará será con el contenido de las preguntas, y también estaría guay añadir más interacciones con Dino y similares por el juego.

**Comment by sagilca** [comment]
- toques al dino y haga cosas
- algunas imágenes sean divertidas
- algunas respuestas sean divertidas
- algunas preguntas sean divertidas
- Algún texto sobre las medallas? Reto "Indiana Jones" conseguido...
